apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-config
  namespace: kiii-namespace
data:
  POSTGRES_DB: "kiii"
  POSTGRES_URL: "postgres-service.kiii-namespace.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: kiii-secret
  namespace: kiii-namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # 'postgres' base64 encoded
  POSTGRES_PASSWORD: YWRtaW4xMjM0NQ==  # 'admin12345' base64 encoded
