apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: events-ns
data:
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: events-ns
type: Opaque
data:
  DATABASE_PASSWORD: YWRtaW4= # 'admin' base64 encoded