apiVersion: v1
kind: ConfigMap
metadata:
  name: db-cm
  namespace: events-ns
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: events-ns
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW4= # 'admin' base64 encoded