apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: events-ns
data:
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  SUPERUSER_USERNAME: admin
  SUPERUSER_EMAIL: admin@admin.com
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: events-ns
type: Opaque
data:
  DATABASE_PASSWORD: YWRtaW4= # 'admin' base64 encoded
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLT0rdmUxYTFwdystIXphYTN5NyQrdGQhJSYhNzZvK2l3MmQ0OHdncnhAZjdzKyluaD0k
  SUPERUSER_PASSWORD: YWRtaW4=