apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deploy
  namespace: events-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: todormitevski/kiii-project:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_KEY
            - name: DATABASE_HOST
              value: db-svc
            - name: DATABASE_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: events-ns
spec:
  selector:
    app: events
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP