apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiii-ingress
  namespace: kiii-namespace
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: "traefik"
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kiii-service
                port:
                  number: 80
    - host: kiii-django.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kiii-service
                port:
                  number: 80
